title                       : Project Jupyter Governance
exclude_patterns            : ["LICENSE.md", "README.md"]
copyright: ""
html:
  extra_footer: |
    <p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
      <a rel="license"
        href="http://creativecommons.org/publicdomain/zero/1.0/">
        <img src="https://licensebuttons.net/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
      </a>
      <br />
      To the extent possible under law,
      <a rel="dct:publisher"
        href="https://jupyter.org">
        <span property="dct:title">Project Jupyter</span></a>
      has waived all copyright and related or neighboring rights to
      <a href="https://github.com/jupyter/governance"><span property="dct:title">Project Jupyter Governance documents</span></a>.
    This work is published from:
    <span property="vcard:Country" datatype="dct:ISO3166"
          content="US" about="https://jupyter.org">
      United States</span>.
    </p>

sphinx:
  config:
    html_show_copyright: false
